# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftSdkTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftSdkTest
  pod 'PubNubSwift', '~> 3.0'

  target 'swiftSdkTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftSdkTestUITests' do
    # Pods for testing
  end

end
