name: iOS CI

on:
  push:
    branches: [ master, ios_test ]
  pull_request:
    branches: [ master, ios_test ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: renatoathaydes/setup-java-sdkman@2.1.1
      with:
        java-version: '11.0.2-open' # The SDKMAN! JDK version to use.
    - name: Install kotlin
      run: source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin 1.5.0
    - name: Install kscript
      run: source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kscript 3.1.0
    - name: Create local.properties with keys
      run: echo -e "\npubnub.subKey=${{ secrets.PUBNUB_SUB_KEY }}\npubnub.pubKey=${{ secrets.PUBNUB_PUB_KEY }}" >> local.properties && cat local.properties
    - name: Create aws credentials file
      run: mkdir $HOME/.aws && echo -e "[default]\naws_access_key_id=${{ secrets.AWS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}\n" > $HOME/.aws/credentials
    - name: Install gpg
      run: brew install gpg
    - name: Setup provisioning profile
      env:
        GPG_PASS: ${{ secrets.GPG_PASS }}
      run: gpg --version && ./scripts/decrypt_secrets.sh
    - name: Install cocoapods
      run: gem install cocoapods
    - name: Building project
      run: cd swiftSdkTest3 && ../scripts/./create_ipa.sh
    - name: Run tests on aws
      env: 
        DEVICE_POOL_ARN: arn:aws:devicefarm:us-west-2:806583214236:devicepool:4e17f447-cc58-4c2b-9167-3924045c5b82/4718d99b-47d5-4a0a-a281-4c12cc594c96
        PROJECT_ARN: arn:aws:devicefarm:us-west-2:806583214236:project:4e17f447-cc58-4c2b-9167-3924045c5b82
      run: source $HOME/.sdkman/bin/sdkman-init.sh && cd swiftSdkTest3 && kscript ../scripts/src/main/kotlin/Script.kt --apkPath Payload.ipa --androidTestApkPath swiftSdkTest3Tests.xctest.zip --projectArn $PROJECT_ARN --devicePoolArn $DEVICE_POOL_ARN
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: swiftSdkTest3/artifacts/
    